### ISSUE TITLE
As a teacher, I want to create multi choice quiz in order to my students can improve their knowledge

### ISSUE THREAD

**Issue by nguyentracthanh** [nguyentracthanh/USTH-SE-2019#8]
Task:
## Design

- [x] Design interface of web app ( Lê Quang Vinh do [that](https://github.com/nguyentracthanh/USTH-SE-2019/issues/29))

- [x] Create button go to quiz test (Lê Quang Vinh do [that](https://github.com/nguyentracthanh/USTH-SE-2019/issues/29))

## Specification
- [x]  Multi choice quiz have more than 5 questions ( where I learned: [HTML](https://www.codecademy.com/courses/learn-html/lessons/intro-to-html/exercises/intro?action=resume_content_item))

- [x]  Multi choice quiz have many levels for students ( Nguyễn Thành Vinh do [that](https://github.com/nguyentracthanh/USTH-SE-2019/issues/28) )

- [x] Sending result to teacher( Nguyễn Trác Thành do that [here](https://github.com/nguyentracthanh/USTH-SE-2019/issues/30))

- [x] Create multi solution ( both true and fail solution Nguyễn Thành Vinh do [that](https://github.com/nguyentracthanh/USTH-SE-2019/issues/28))
[Learn](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/b7375232b119453ba87336338b8eb8a0/a8f7d83d3851495d8e676efb4984136b/1?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%407389d1be989e4e93bff2fc619117d7d7)
## Testing

- [x] Testing code in many browsers ( Nguyễn Trác Thành do [that])(https://drive.google.com/drive/folders/1j_RtWX8E0ONpxIBb-q-lfp-0Cq4oQJJR?usp=sharing)
## Upload to website

- [x] Push source code to web and make it can run ( Nguyễn Trác Thành do [that](https://github.com/nguyentracthanh/USTH-SE-2019/issues/31))

### Product
Link of group product: http://fiprodsevtv.tk/
